"""class-student relationship

Revision ID: 234041f1fdfc
Revises: 88b68eec5a28
Create Date: 2020-04-14 15:20:08.314707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234041f1fdfc'
down_revision = '88b68eec5a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentclassinfo',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['schoolclass.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentclassinfo')
    # ### end Alembic commands ###
